New Makeshift weaponry: Ross Rifle and Huot Conversion!
austation/austation pull request #2137
Opened 2020-08-16 22:27 UTC by PapaSejd

## About The Pull Request

Adds 2 new weapons and a design for the autolathe.

- Ross Rifle. Once a standard rifle on the Canadian military in WW1, this rifle is now craftable in the recipe menu, and requires roughly the same materials as its other makeshift brothers. Does 30 damage and a flat 10% to jam. Holds 5 .303 bullets.

![image](https://user-images.githubusercontent.com/63993176/90345315-9481d000-dfed-11ea-9e0e-44f41940062a.png)

- Huot Conversion. This conversion recipe can convert the Ross rifle into another variant of it, the Huot Automatic. Designed in 1916, this automatic rifle holds 25 shots in a drum mag, with a flat chance of 5% to jam. Requires a firing pin (new firing system) and more materials to create than its other brothers. It has a firing rate of 3 (same as stetchkin).

![image](https://user-images.githubusercontent.com/63993176/90345353-e7f41e00-dfed-11ea-8b63-2cd3b7feb34d.png)

- Adds the .303 bullet to hacked Autolathe designs.

## Why It's Good For The Game

To complete the trifecta of weapon types, rifles are now added for players to craft. Now assistants can find their niche when trying to kill all of security!

## Changelog
:cl:
add: added rifles, bullets and more
/:cl:

2020-08-17 00:47 UTC, thelaughingbomb commented
Nice

2020-08-19 08:50 UTC, thelaughingbomb commented on austation/code/datums/components/crafting/recipes.dm
> +	/datum/crafting_recipe/huotconvert
I think travis is being pissy about the space at the start of the line

2020-08-21 02:54 UTC, TheFakeElon commented on austation/code/modules/projectiles/guns/ballistic/automatic.dm
> +		chambered = null
You can instantly unjam by pressing z, maybe add an action timer so it actually does something

2020-08-21 02:55 UTC, TheFakeElon commented on austation/code/modules/projectiles/guns/ballistic/rifle.dm
> +	desc = "Already a terrible rifle, this improvised Ross rifle should be able to take care of security officers, maybe."
Maybe something more along the lines of explaining the weapon

2020-08-21 02:56 UTC, TheFakeElon commented on austation/code/modules/projectiles/guns/ballistic/automatic.dm
> +	fire_rate = 3
90 DPS for a makeshift weapon, pls no

2020-08-21 02:58 UTC, TheFakeElon commented on austation/code/datums/components/crafting/recipes.dm
> +				/obj/item/firing_pin/ = 1)
That’s pretty cheap considering how strong this weapon is, rivalling some syndicate and security exclusive weapons.

2020-08-21 02:58 UTC, TheFakeElon commented on austation/code/modules/projectiles/guns/ballistic/automatic.dm
> +		chambered = null
And yes, I know this is how the makeshift pistol does it but it’s nowhere near as strong as this.

2020-08-24 13:13 UTC, MCterra10 commented
testmerging

2020-08-25 20:25 UTC, PapaSejd commented
edited to include #2171 changes

2020-08-30 00:52 UTC, MCterra10 requested changes
can you knock the damage down a bit? 75dps with only a 5% chance to jam and a 25 round mag is pretty ridiculous

2020-08-30 16:32 UTC, PapaSejd commented
Aight ill drop it down to 15, it will render the ross essentially useless but I guess its only meant to be a stepping stone for the huot

2020-09-06 01:42 UTC, MCterra10 commented
Conflicts my guy

2020-09-06 03:01 UTC, PapaSejd commented
Im gonna have to close this for now and reopen another PR cause the branch was deleted lol

2020-09-06 03:01 UTC, closed without merging

2020-09-06 04:49 UTC, MCterra10 commented
f