Viro AUStation Sensibilities Reconfigure
austation/austation pull request #2178
Opened 2020-08-27 05:47 UTC by MrLostman

## About The Pull Request
**Bee Infestation**
-symbiotic and honey producing have been separated
`resistance 6 and 8 respectively`
-bee spawn chance linked to stage speed
`prob(25 + clamp(A.properties["stage_rate"] * 5, -25, 70)`
-can stop it from making bees but removes royal jelly,and halfs the amount of honey
`resistance 12`
**Pituitary Disruption**
-no longer spawns meta grudges
-no longer makes you vomit all over the station
-no longer randomises organs
**Nanite Symbiosis**
-no longer causes glitches
**Self Resp**
-farting removal modularized
**Viral Aggressive Meta**
-If it cures the virus does not make them immune
**Weight Loss**
-threshold to make it stop you from becoming fat
`resistance 8`
**Spiked Skin**
-returned to 60 armour cap

### Stat Changes
stealth, resistance, stage speed, trans
**Deafness**
-1,-2,-1,-3 -> 0, -2, -1, -1
**Fever**
-1,3,3,2 -> 0,3,3,2
**Spontaneous Combustion**
1,-2,-3,-3 -> 1,-1,-2,-1
**Necrotizing Fasciitis**
-3,-3,0,-4 -> -1,-1,0,-1
**Narcolepsy**
1,-2,-3,-2 -> 1,-1,-2,-1
**Hyphema**
-1,-3,-4,-2 -> -1,-2,1,-1
**Vomiting**
-2,1,0,2 -> -3,2,1,3

## Changelog
:cl:
balance: rebalanced stats of deafness, fever, spontaneous combustion, necrotizing fasciitis, narcolepsy, hyphema and vomiting
refactor: modularized self resp fart removal
tweak: bee infestation symbiotic and honey producing have been separated, bee spawn chance linked to stage speed and a no bee threshold
tweak: pituitary disruption, superficial healing and nanite symbiosi has had zesko grief code removed
tweak: viral aggressive meta doesn't make host immune if it cures
tweak: weight loss threshold to make it stop people from getting fat
tweak: spiked skin armour reverted to 60
/:cl:

2020-08-27 06:07 UTC, zeskorion commented
> tweak: spiked skin armour reverted to 60


lol

2020-08-27 06:29 UTC, Dingo-Dongler commented on austation/code/datums/diseases/advance/symptoms/heal.dm
> +					<b>Stage Speed 12:</b> The disease heals brute damage incredibly fast, but deteriorates cell health and causes tumors to become more advanced. The disease will also regenerate lost limbs"
```suggestion
					<b>Stage Speed 12:</b> The disease heals brute damage incredibly fast, but deteriorates cell health. The disease will also regenerate lost limbs"

```

2020-09-03 07:15 UTC, MCterra10 requested changes
`code/datums/diseases/advance/symptoms/oxygen.dm`
please ensure you are not changing line endings

2020-09-11 08:05 UTC, MrLostman commented
merge it

2020-09-15 23:59 UTC, TheFakeElon commented
read Terra's review smh, you haven't fixed your line endings

2020-09-16 01:40 UTC, closed without merging