Bonfires push heat
austation/austation pull request #2207
Opened 2020-09-03 04:34 UTC by jbox144

## About The Pull Request

After realising bonfires no longer pushed heat I was shook. No longer could one heat their maint home with a bonfire, or huddle around a comfy campfire on lavaland. They were cold and dead.

Saddened, I turned to dream maker to solve my issue. It disagreed, but I forced it to obey.

And now we have this.

This PR makes bonfires push heat to the environment. However, unlike original bonfires, they will only push heat up to a certain value. For now, it's set to 25C. They work with the same efficiency as T1 space heaters, but unlike space heaters, cannot cool the environment.

I also fixed some ugly indentation on some code in the same file, don't mind that.

## Why It's Good For The Game

![image](https://user-images.githubusercontent.com/40789662/92071551-5e688c80-edf2-11ea-863a-cd9a87090390.png)

## Changelog
:cl:
tweak: Bonfires now push heat to the environment, heating up the air around it to 25C, with the same efficiency as a T1 space heater.
code: Fixed some ugly indentation in towercap.dm
/:cl:

2020-09-03 05:41 UTC, TheFakeElon commented
25c bonfire :flushed:

2020-09-03 07:44 UTC, Ohagi-Chan commented
Lavaland is often 40+ degrees and it doesn't hurt anything.
Also check that your fire isn't trying to reduce the temperature of lavaland down to 25.

2020-09-03 09:16 UTC, jbox144 commented
> Lavaland is often 40+ degrees and it doesn't hurt anything.
> Also check that your fire isn't trying to reduce the temperature of lavaland down to 25.

It won't, trust me on thta

2020-09-15 23:43 UTC, TheFakeElon requested changes
mostly good to go! Just need to fix your line endings :)

2020-09-26 02:28 UTC, MCterra10 approved these changes

2020-09-26 02:29 UTC, merged