Drone refresh 2
austation/austation pull request #2357
Opened 2020-10-09 07:48 UTC by jbox144

## About The Pull Request

Reintroduces drones onto the station. Drones now have access to a built in radio, which can recieve from the common and engineering channels, but cannot transmit. Drones can also speak in binary, and understand common.

Drones also now also have a modified lawset, which lets them interact with silicons. Basically, it makes drones less boring.

This may be unbalanced, but I'd like to see this change tested first. I have more changes to drones underway, to better control drones and prevent them being exploited.

## Why It's Good For The Game

Drones are an underappreciated mob, with a lot of potential. I just think they lack any interactability, which often makes drone gameplay very dull.

## Changelog
:cl:
add: Drones get a built-in radio, connected to the common and engineering channels. It cannot transmit however.
add: Drones can be built at mech fabricators, once basic robotics is researched, at the cost of iron, glass and some gold.
tweak: Drones can speak in silicon, and can understand common. Derelict drones cannot speak silicon.
tweak: Drones can speak on binary with the :b prefix. The drone exclusive channel has been moved to the :d prefix. Derelict drones can only use dronechat.
/:cl:

2020-10-10 09:06 UTC, amidoingitright commented
A use for the drone pinger for PDA cartridges at last

2020-10-11 22:15 UTC, TheFakeElon commented
Don’t let them speak with IPCs

2020-10-12 05:57 UTC, MCterra10 requested changes

2020-10-12 05:57 UTC, MCterra10 commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +								/datum/language/common = list(LANGUAGE_ATOM))
remove common and machine understanding, please

2020-10-12 05:57 UTC, MCterra10 commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +		return .
```suggestion
		return ..()
```

2020-10-12 05:57 UTC, MCterra10 commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +	return FALSE // If your not a drone, no drone chat for you
please add a trailing newline to the end of your file

2020-10-12 05:58 UTC, MCterra10 commented
Also this really doesn't fix the problem that drones are just better, more versatile borgs, now in far more literal sense since they can speak on binary and communicate with borgs and the AI. Idk chief.

2020-10-16 01:22 UTC, TheFakeElon commented
I’m torn on this one, I agree with Terra here. Silicons are (usually) more fun to play with whereas drones are just the stronger, zero crew interaction version.

2020-10-19 02:08 UTC, ZombiesVsPlants commented
ah that's fine, just rebalance borgs to be stronger than humans like intended so you have to trade your strength away for hands.

2020-10-19 02:54 UTC, TheFakeElon commented
**”like intended”**

Borgs are supposed to be specialised in certain tasks rather than being a jack of all trades like humans

2020-10-19 02:55 UTC, TheFakeElon commented
Drones are an unbalanced mix of the two

2020-10-19 04:45 UTC, ZombiesVsPlants commented
standard borg is literally jack of all trades

2020-10-19 23:39 UTC, TheFakeElon commented
Standard borg is the jack of no trades. It can’t do anything particularly well.

2020-10-20 02:05 UTC, ZombiesVsPlants commented
well then, needs a buff obviously.

2020-10-20 03:51 UTC, TheFakeElon commented
Default borg shouldn’t be a jack of all trades. A “general purpose borg” defeats the whole purpose of a borg. I don’t think they should be removed (I’ll miss meme borg) like what TG did but they don’t need to be “buffed” either

2020-10-20 03:51 UTC, TheFakeElon commented
ANYWAY this is getting off topic.

2020-10-20 05:12 UTC, jbox144 commented
I'd be happy with a testmerge

2020-10-21 00:51 UTC, MCterra10 commented
I'm not *happy* about these changes, but I guess elon can go ahead with a testmerge

2020-10-21 00:57 UTC, TheFakeElon commented
I was waiting for your opinion. I was pretty against this but on the other hand, I remember how fun ghost drones were on goon, which were basically this.

2020-10-22 04:24 UTC, MCterra10 commented
testmerged

2020-10-30 02:10 UTC, MCterra10 commented
I think it's been testmerged long enough, I'll check with players

2020-11-02 23:09 UTC, TheFakeElon approved these changes

2020-11-03 00:09 UTC, MCterra10 requested changes

2020-11-03 00:09 UTC, MCterra10 commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +	return ..() // Anything that isn't a drone is handled normally.
remove binary chat, this is pretty bad. other than that, I'm okay to merge

2020-11-08 11:17 UTC, MCterra10 requested changes

2020-11-08 11:17 UTC, MCterra10 commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +							/datum/language/machine = list(LANGUAGE_ATOM))
remove ability to speak machine and this is ok to merge

2020-11-08 23:25 UTC, TheFakeElon commented on austation/code/modules/mob/living/simple_animal/friendly/drone/say.dm
> +							/datum/language/machine = list(LANGUAGE_ATOM))
```suggestion
	spoken_languages = list(/datum/language/drone = list(LANGUAGE_ATOM))
```

2020-11-08 23:31 UTC, TheFakeElon approved these changes

2020-11-09 21:57 UTC, TheFakeElon commented
I didn't notice any issues during test merge

2020-11-09 21:57 UTC, merged