Borg hug module now provides a mood buff
austation/austation pull request #2395
Opened 2020-10-15 05:04 UTC by thelaughingbomb

## About The Pull Request

Huge silicon buff!

## Why It's Good For The Game

Hugging module actually does something now.
Its exact same mood gained from being hugged by a person.

## Changelog
:cl:
add: Hug module now provides a mood buff
/:cl:

2020-10-15 22:27 UTC, TheFakeElon approved these changes

2020-10-16 06:06 UTC, ZombiesVsPlants commented
The Silicon buff we needed

2020-10-16 13:50 UTC, MCterra10 requested changes

2020-10-16 13:50 UTC, MCterra10 commented on code/game/objects/items/robot/robot_items.dm
> +					if(is_species(M, /datum/species/human/felinid))// Austation -- Borg hugs provide mood
SMH NOT EVEN USING
```dm
// austation begin -- <msg>
```
what is the world coming to.

2020-10-17 06:49 UTC, merged