Fix science shuttle+dock
austation/austation pull request #2456
Opened 2020-10-23 08:37 UTC by Ohagi-Chan

## About The Pull Request
fixes some mapping errors on the science outpost shuttle and its station-side dock.  some other changes were made to better accomodate the new shape of the shuttle

## Why It's Good For The Game
looks a little better

## Changelog
:cl:
tweak: changed the shape of the science outpost shuttle
tweak: changed the shape of the science outpost shuttle station dock
/:cl:

2020-10-23 08:40 UTC, Ohagi-Chan commented
when I tried to add change notes to the map it caused the map to be unreadable  (I believe this is because I can't add comments between the curly brackets in the later stages of the file when it is placing all of the object keys onto the cartesian grid.)

2020-10-23 21:43 UTC, TheFakeElon commented
Yeah, don’t touch map file directly. Instead make a copy of the shuttle and give it “austation” somewhere in its name. Change the code reference from the normal one to that and viola, you can now comment that line

2020-10-23 21:47 UTC, Ohagi-Chan commented
> Yeah, don’t touch map file directly. Instead make a copy of the shuttle and give it “austation” somewhere in its name. Change the code reference from the normal one to that and viola, you can now comment that line

Thanks, I will give that a shot tonight.

2020-10-28 06:18 UTC, Ohagi-Chan commented
Is there anything that needs to be changed?

2020-10-29 03:12 UTC, MCterra10 requested changes

2020-10-29 03:12 UTC, MCterra10 commented on _maps/map_files/Mining/Lavaland.dmm
> +	roundstart_template = /datum/map_template/shuttle/science/aus;
why?
just change the docking port variables in the code, don't make an entirely new one *and then* put it in the lavaland map

2020-10-29 03:12 UTC, MCterra10 commented on code/datums/shuttles.dm
> +	can_be_bought = FALSE
just modify the suffix var on the original one, map edits are so so much worse than just changing code

2020-10-29 07:29 UTC, Ohagi-Chan commented
I have made the requested changes

2020-10-30 00:04 UTC, TheFakeElon commented
Single white space in lavaland dmm, day ruined 😔

2020-10-30 02:09 UTC, MCterra10 approved these changes
looking poggers

2020-11-02 01:07 UTC, merged