Discord roundend summary
austation/austation pull request #2548
Opened 2020-11-10 01:33 UTC by jupyterkat

## About The Pull Request

Makes scomo display round end statistics

## Why It's Good For The Game

why not

## Changelog
:cl:
add: Roundend summaries are now on discord
/:cl:

2020-11-10 01:44 UTC, ZombiesVsPlants commented
Based

2020-11-10 03:09 UTC, TheFakeElon commented
Couldn't you modularise this? Just comment out the original code if you can't override

2020-11-10 04:08 UTC, jupyterkat commented
I’ll make a separate proc for it later

2020-11-15 02:01 UTC, MCterra10 requested changes
I made a dedicated channel for these, change the tags

2020-11-15 02:01 UTC, MCterra10 commented on austation/code/_HELPERS/roundend.dm
> +		send2chat(discordmsg, "status")
```suggestion
		send2chat(discordmsg, "roundend")
```

2020-11-15 02:01 UTC, MCterra10 commented on austation/code/_HELPERS/roundend.dm
> +		send2chat(discordmsg, "status")
```suggestion
		send2chat(discordmsg, "roundend")
```

2020-11-15 02:05 UTC, MCterra10 approved these changes

2020-11-15 02:13 UTC, merged