Disables random events during sandbox
austation/austation pull request #2604
Opened 2020-11-19 12:52 UTC by Chessus

## About The Pull Request

Random events are now disabled during sandbox mode. Sets the allow_random_events config option to false at the start the game mode. Can be reenabled under Server tab or commented out if needed.     

## Why It's Good For The Game

-Makes sandbox peaceful 
-Removes the annoyince of metorites, anomalies, power-outs and ect so players can focus on their projects or other.
-Removes the circumvention of Rule 0, Don't be a dick. Antags are removed from a non-antag mode. 

## Changelog
:cl:
tweak: Random events are now disabled by default on Sandbox mode. 
/:cl:

2020-11-19 12:53 UTC, Chessus commented
Ran for over an hour and no events spawned during that time

2020-11-21 00:38 UTC, MCterra10 requested changes

2020-11-21 00:38 UTC, MCterra10 commented on code/game/gamemodes/sandbox/sandbox.dm
> +	//Enables player spawing
please surround your core code changes with
`//austation begin -- <reason for change>`
and
`//austation end`

2020-11-21 00:39 UTC, MCterra10 commented on code/game/gamemodes/sandbox/sandbox.dm
> +	//Enables player spawing
also you should probably just force it to false, instead of inverting the config value.

2020-11-23 00:53 UTC, Chessus commented
June

2020-11-23 00:53 UTC, closed without merging