Rebalances material availability in cargo
austation/austation pull request #2806
Opened 2020-12-28 22:40 UTC by Ohagi-Chan

## About The Pull Request

Makes materials more available in cargo for rounds where there are no miners.  A fast way to trade convenience for THOUSANDS of credits.
All crate (including previously existing crates) prices are balanced to be worth 30% more than the value you could make back by selling the materials and the crate they came in.
Wooden byproducts such as ore boxes and coffins can be sold to make back the value of the wood, plus 250c (down from around 500)
Diamonds have had their price halved because it was honestly insane and nobody sells diamond anyway.

## Why It's Good For The Game

This will help on the very rare occasions when miners have not joined (more important in lowpop seasons) and is a step in the direction needed before Lostman can even begin to consider removing the mining minigame.
IMPORTANT: This PR does not remove mining or affect the availability of mined materials, it only puts materials into cargo at exorbitant prices.

## Changelog
:cl:
add: copper to cargo
add: silver to cargo
add: plasma to cargo
add: titanium to cargo
add: gold to cargo
add: uranium to cargo
add: diamond to cargo
balance: repriced plasteel imports
balance: repriced wood byproduct imports
balance: repriced diamond exports
/:cl:

2020-12-29 02:21 UTC, Ohagi-Chan commented
Nus has brought up an important point with me, in private.  By halving the price of diamonds, I have hurt their ability to contribute towards a pirate victory.

Diamonds were 500 export, I have reduced them to 250.
This will need to be considered, if numbers need to be changed.

2020-12-29 03:55 UTC, TheFakeElon requested changes
These changes can be easily modularized. Try to use words in typepaths instead of numbers too, use `gold_fifty` instead of `gold50`. Or use `gold/fifty` if you want to make it a child

2020-12-29 04:01 UTC, Ohagi-Chan commented
> These changes can be easily modularized. Try to use words in typepaths instead of numbers too, use `gold_fifty` instead of `gold50`. Or use `gold/fifty` if you want to make it a child

This is the convention that the other datums were already using.  If I change the ones I've added to gold_50, then I should do the same to all the existing datums as well.

2021-01-07 06:51 UTC, Ohagi-Chan commented
Bee did a similar pr recently. 
I wasn't too se how that goes and learn from it.

2021-01-07 06:51 UTC, closed without merging