Overdose and Addiction Are Triggered When Reagents Are ABOVE Threshold
austation/austation pull request #3045
Opened 2021-02-13 04:46 UTC by mudzbe

## About The Pull Request

This PR changes both addiction and overdose to only trigger when reagents are **above** their respective thresholds, as opposed to **above and equal** to the threshold. 
This means that if the threshold is 30u, having 30u in your bloodstream will not trigger either effect, whereas 30.1 units will. Before this was the opposite: Having 30u in the bloodstream WOULD trigger the effects, but 29.9 wouldn't.  

## Why It's Good For The Game

It makes chems less annoying, the previous system is stupid and I hate it. You can now have 0.1 more chems without experiencing addiction or overdose.

## Changelog
:cl:
tweak: Overdose and addiction are triggered when reagents are ABOVE threshold as opposed to ABOVE AND EQUAL to the threshold
/:cl:

2021-02-13 04:57 UTC, mudzbe commented
Now I think about maliciously injecting chems, really the whole system is stupid how there can be a binary overdose/not overdose. How does an extra .1u magically make you start shooting blood out of your eyeballs when you were fine without it

2021-02-13 12:47 UTC, Chessus commented
Nice. It's always irked me.

2021-02-17 05:54 UTC, TheFakeElon requested changes
Needs an austation change note

2021-02-17 05:54 UTC, TheFakeElon commented
Preferably include the PR number

2021-02-17 23:26 UTC, TheFakeElon commented on code/modules/reagents/chemistry/holder.dm
> +						if(R.volume > R.overdose_threshold && !R.overdosed) //This is a certified AUStation code moment, PR: #3045. Changed from >= to >
Made me chuckle but you should probably follow the standard way to do it.

`//austation -- [comment]`

2021-02-24 00:55 UTC, MCterra10 requested changes

2021-02-24 00:55 UTC, MCterra10 commented on code/modules/reagents/chemistry/holder.dm
> +						if(R.volume > R.overdose_threshold && !R.overdosed) //AUStation, PR: #3045 -- Changed from >= to >
```suggestion
						if(R.volume > R.overdose_threshold && !R.overdosed) // austation -- PR: #3045 Changed from >= to >
```

2021-02-24 00:55 UTC, MCterra10 commented on code/modules/reagents/chemistry/holder.dm
> +						if(R.volume > R.addiction_threshold && !is_type_in_list(R, cached_addictions))
```suggestion
						if(R.volume > R.addiction_threshold && !is_type_in_list(R, cached_addictions)) // austation -- PR: #3045 Changed from >= to >
```

2021-02-28 05:54 UTC, MCterra10 approved these changes

2021-02-28 05:54 UTC, TheFakeElon approved these changes

2021-02-28 05:54 UTC, merged