ports tgui list but I made it better
austation/austation pull request #3344
Opened 2021-04-19 02:38 UTC by jupyterkat

## About The Pull Request

cringe ass nae nae francy nancy doesn't want it on bee

I will modularize the modularizable parts soon

## Why It's Good For The Game

yes

## Changelog
:cl:
add: Tgui input lists
/:cl:

2021-04-26 13:26 UTC, MCterra10 requested changes

2021-04-26 13:26 UTC, MCterra10 commented on tgui/packages/tgui/styles/main.scss
> +@include meta.load-css('./interfaces/ListInput.scss');
```suggestion
// Interfaces
// austation -- adds tgui lists
@include meta.load-css('./interfaces/ListInput.scss');
```

2021-04-26 13:27 UTC, MCterra10 commented
other than that, all just simple one liner changes. should be fine to merge.

2021-05-06 22:10 UTC, celotajstg commented
What makes it better than the tg implementation?

2021-05-06 22:16 UTC, jupyterkat commented
> What makes it better than the tg implementation?

go figure

2021-05-12 09:34 UTC, MCterra10 approved these changes

2021-05-21 16:41 UTC, MCterra10 commented
resolve conflicts I'll actually merge it this time

2021-05-22 10:51 UTC, merged