Sprite Revert Tools & Parts : AKA Bee Spriters Still Suck
austation/austation pull request #3684
Opened 2021-06-26 03:21 UTC by MrLostman

![unknown](https://user-images.githubusercontent.com/50007631/123500446-35233080-d692-11eb-9cd9-707af909aaaa.png)

## Changelog
:cl:
imageadd: added old tools and parts
/:cl:

2021-06-26 15:22 UTC, lordScrubling commented
bee part sprites and inducers look way better
emergency welding tool wasnt changed at all

2021-06-26 20:56 UTC, MrLostman commented
> 
> 
> bee part sprites and inducers look way better
> emergency welding tool wasnt changed at all
> also, what about the ranged analyzer and rpd?

why is a bee loser so intrested in these sprite reverts? they your shitty sprites?

2021-06-27 04:05 UTC, lordScrubling commented
you got some beef with anyone from bee

2021-06-27 05:04 UTC, MrLostman commented
bee

2021-07-05 04:04 UTC, MCterra10 commented
@MrLostman merge conflict

2021-07-06 05:27 UTC, MCterra10 requested changes

2021-07-06 05:27 UTC, MCterra10 commented on austation/code/game/objects/items/tools/weldingtool.dm
> +#define WELDER_FUEL_BURN_INTERVAL 26
stray define

2021-07-06 05:30 UTC, MCterra10 approved these changes

2021-07-06 05:32 UTC, merged