Makes cyborgs able to do dissections
austation/austation pull request #3850
Opened 2021-07-22 01:54 UTC by ZombiesVsPlants

## About The Pull Request

Allows medical cyborgs to dissect corpses with the experimental dissection technology

## Why It's Good For The Game

![Stopped Racism](https://user-images.githubusercontent.com/60122079/126580510-4b74fe63-4b02-4545-b11b-86318f40ac5e.png)

## Changelog
:cl:
balance: Allows medical cyborgs to dissect carbons using the experimental dissection surgery
/:cl:

2021-07-22 02:07 UTC, ZombiesVsPlants commented
mfw it fails
I'll fix it tomorrow maybe I've got work to do

2021-07-23 14:01 UTC, lordScrubling commented on code/modules/surgery/advanced/bioware/experimental_dissection.dm
> + 	if(target.stat != DEAD)
```suggestion
	if(target.stat != DEAD)
```
bruh i bet it's cause you used space instead of tab

2021-07-26 03:46 UTC, ZombiesVsPlants commented
Cheers @lordScrubling

2021-07-27 02:07 UTC, MCterra10 requested changes
formatting for this removal is pretty wack.
as per the README in the austation folder, if disabling code in the main files, you need to use block commits like so:
```dm
/* austation begin -- disabled some code
<disabled code is here>
austation end */
```

Also don't change the position of the code you disable. I'm not sure why you're moving it down to the bottom lol

2021-07-29 02:24 UTC, ZombiesVsPlants commented
You're completely right terra but i'll fix this at a later date

2021-07-29 02:24 UTC, closed without merging