Bags and backpacks can now be emptied into disposal bins
austation/austation pull request #4000
Opened 2021-08-14 06:29 UTC by Ohagi-Chan

## About The Pull Request
Now you can empty bags into disposal bins to dump out all the contents, the same way you would with a trash bag.
This was made with botany bags in mind especially.

## Why It's Good For The Game
Makes housekeeping a lot easier.
The aforementioned botany bags will benefit greatly because now you have a fast and efficient method to remove all your dud seeds without dumping them on the floor.

## Changelog
:cl:
tweak: Disposal bins now react to bags and backpacks by emptying their contents instead of disposing the bag, if they had any.
/:cl:

2021-08-14 06:30 UTC, Ohagi-Chan commented
Hold the phone, I just remembered that Science would like to do the same with their RPEDs.
Sure, they could transfer the spare components into a bag from the floor, but the whole point of this PR is to cut out silly extra steps.

2021-08-14 06:37 UTC, Mick1299 commented
Science can already do it with the bluespace rped, just click and drag to a bin/ Not sure if the same technique works for other storage devices, or if its unique to bluespace rped.

2021-08-14 07:30 UTC, Ohagi-Chan commented
For the life of me I can't find the code that handles that, even after searching for many key words in the code and in merged PRs.
But it seems to be true. That much I've tested for myself.

All the same, this PR works slightly different and lets you dump things into the bin with a click instead of a click-drag.
It's up to Terra if he'd like to add that feature, or if the current feature is good enough/ better (in my code, you can't dump an RPED, bag or backpack with contents inside it, you have to dump the contents first and then click again).

2021-08-14 07:38 UTC, Singularity69 commented
Is there a delay? I don't want to accidentially empty all of my gamer loot to the recycler

2021-08-14 07:45 UTC, Ohagi-Chan commented
> Is there a delay? I don't want to accidentially empty all of my gamer loot to the recycler

I can easily add a delay

One advantage to my method rather than the click-drag method is that I've made it a visible action, so you are warned when you dump items by clicking the bin and nearby people can also spy the action.

2021-08-23 06:46 UTC, MCterra10 requested changes
You also need to comment out the parent proc at https://github.com/austation/austation/blob/279cc79b706617680ba2e79df5b0ac18fa64b74d/code/modules/recycling/disposal/bin.dm#L269 because it still has code for trashbags which is called every time this new proc runs and doesn't dump; keep your code tidy please.

2021-08-23 06:46 UTC, MCterra10 commented on austation/code/modules/recycling/disposal/bin.dm
> +	)
You don't type a list of typepaths. This isn't an object list.
Also use typecaches.
```suggestion
	var/static/list/store_list = typecacheof(list(
		/obj/item/storage/part_replacer,
		/obj/item/storage/bag,
		/obj/item/storage/backpack
	))
```

2021-08-23 06:46 UTC, MCterra10 commented on austation/code/modules/recycling/disposal/bin.dm
> +		B.update_icon()  //  We are overriding trash bags with this code, so we have to make sure they follow their routine.
This code is trash and needs a refactor, and to use the typecache
```suggestion
	if(store_list[I.type] && length(I.contents))
		var/obj/item/storage/S = I
		user.visible_message("<span class='warning'>[user] begins to empty \the [I] into \the [src].</span>", "<span class='warning'>You begin to empty \the [I] into \the [src].</span>")
		if(do_after(user, 1 SECONDS, src))
			var/datum/component/storage/STR = S.GetComponent(/datum/component/storage)
			for(var/obj/item/O in S.contents)
				STR.remove_from_storage(O,src)
			S.update_icon() 
		else
			to_chat(user, "<span class='warning'>You stop emptying \the [I].</span>")
	else
		return ..()
```
you're welcome

2021-08-30 07:53 UTC, MCterra10 commented
honestly after consideration I think click drag is fine. I'd find it annoying to have to click twice to put a backpack in the bin

2021-08-30 07:53 UTC, closed without merging