Sentient Disease point economy rebalance
austation/austation pull request #4229
Opened 2021-09-25 11:30 UTC by Ohagi-Chan

## About The Pull Request
Rebalances all sentient disease powers more accessible, earlier into the game.
This has been done to ensure that diseases get access to more of their powers within the scope of AuStation, where pop expectations are much lower than on Beestation.

## Why It's Good For The Game
Sentient Diseases are a very frustrating antag to play because they rarely get access to any of their more interesting abilities.  This has the knock-on effect that they are uninteresting for the crew to encounter as well, because they only ever face diseases with the sparse few symptoms from the beginning of the list.
Sentient Diseases face this problem because of two issues in particular:
1) Their cost requirements are catered towards servers that experience larger, denser populations than the environment here at austation.
2) Sentient Diseases are often stomped out very quickly, due to both the lack of positive abilities available at the start of the list, that might encourage the crew to keep it, but also because of the lack of powerful offensive and defensive options that would allow it to put up a better fight.

If Sentient Diseases were to be given more leeway on Austation, allowed to be buffed to a stronger early game than on other stations, then I believe we would find an equilibrium in which Sentient Diseases have the intended impact on our games.

## Changelog
:cl:
tweak: Sentient disease - involuntary sneezing cost reduced to 1 from 2
tweak: Sentient disease - involuntary Secrete Infection cost reduced to 1 from 2
tweak: Sentient disease - mild symptom cost reduced to 1 from 2
tweak: Sentient disease - mild symptom required total reduced to 2 from 4
tweak: Sentient disease - medium symptom cost reduced to 2 from 4
tweak: Sentient disease - medium symptom required total reduced to 4 from 8
tweak: Sentient disease - medium positive symptom cost reduced to 3 from 5
tweak: Sentient disease - severe symptom required total reduced to 8 from 16
tweak: Sentient disease - severe positive symptom cost reduced to 4 from 8
/:cl:

2021-09-28 04:47 UTC, MCterra10 commented
you could simplify your entire changelog into "halved all costs for sentient diseases" and it would make far more sense

2021-09-28 21:17 UTC, Ohagi-Chan commented
It would be easier to read, but it's not accurate.
However, as you wish.

2021-10-06 06:25 UTC, TheFakeElon requested changes
The change is welcome 👍, but you have to be careful when balancing through pop as it can make certain things round stomp during highpop. 

Could you make disease prices check server population before applying the buff? Ideally making the threshold config controlled. ~15-20 would be a good ballpark max threshold IMO

2021-10-06 10:08 UTC, Ohagi-Chan commented
> The change is welcome 👍, but you have to be careful when balancing through pop as it can make certain things round stomp during highpop.
> 
> Could you make disease prices check server population before applying the buff? Ideally making the threshold config controlled. ~15-20 would be a good ballpark max threshold IMO

I agree with this plan and will make a new commit as soon as I work out how to check the pop at round start.
Would it be fine to have this piggyback off the skeleton shift switch?

2021-11-12 07:55 UTC, MCterra10 commented
closing due to inactivity

2021-11-12 07:55 UTC, closed without merging