Hypodermic Needles Don't Penetrate Armour
austation/austation pull request #4363
Opened 2021-10-31 04:29 UTC by MrLostman

## About The Pull Request
As the title says

## Changelog
:cl:
balance: hypodermic needles no longer penetrate armour
/:cl:

2021-10-31 04:35 UTC, MCterra10 commented
Botany nerf wojack

2021-10-31 05:24 UTC, Mick1299 commented
based logging for admins

2021-11-12 13:23 UTC, MCterra10 requested changes

2021-11-12 13:23 UTC, MCterra10 commented on austation/code/modules/mob/living/carbon/human/human.dm
> +
why are you overriding this proc? I don't see any changes except putting the message in a variable and moving the false return to a catch-all at the end. what's the point?

2021-11-21 02:31 UTC, closed without merging