Gympie Gympie Additions
austation/austation pull request #4460
Opened 2021-11-19 09:09 UTC by DrDuckedGoose

## About The Pull Request

Adds the ability to rename spawned Gympies through editing seed-names.

## Why It's Good For The Game

Botanists should be able to annotate the species of Gympie to effectively communicate their intentions to allies. 

## Changelog
:cl:
adds: Gympies inherit edited seed-names
/:cl:

2021-11-24 03:27 UTC, MCterra10 requested changes

2021-11-24 03:27 UTC, MCterra10 commented on austation/code/modules/hydroponics/grown/gympie_gympie.dm
> +			name = new_name
more descriptive name should be used imo
```suggestion
			name = "pack of [new_name] seeds"
```

2021-11-24 03:27 UTC, MCterra10 commented on austation/code/modules/hydroponics/grown/gympie_gympie.dm
> +		return ..()
this else is redundant, since you already return anyway if the if block triggers
```suggestion
	return ..()
```

2021-11-24 05:51 UTC, DrDuckedGoose commented
I don't think the file-view updated, but the changes were made, however.

2021-11-26 04:39 UTC, MCterra10 requested changes

2021-11-26 04:39 UTC, MCterra10 commented on austation/code/modules/hydroponics/grown/gympie_gympie.dm
>  		if(S)
no need to store this in a variable, you can just check it directly
```suggestion
		if(reagents.has_reagent(awaken_reagent))
```

2021-11-26 05:05 UTC, MCterra10 approved these changes

2021-11-26 05:09 UTC, merged