Fix Floral Spines
austation/austation pull request #4835
Opened 2022-03-06 04:55 UTC by DrDuckedGoose

## About The Pull Request

Fixes Floral Spines overlay & embed bug

## Why It's Good For The Game

Gross visual is bad

## Changelog
:cl:
Fix: Fixes Floral Spines overlay issue
Tweak: Changes embed specification to superior. 
/:cl:

2022-03-06 07:40 UTC, MCterra10 requested changes

2022-03-06 07:40 UTC, MCterra10 commented on code/modules/hydroponics/grown/misc.dm
> +	genes = list(/datum/plant_gene/trait/plant_type/weed_hardy, /datum/plant_gene/trait/invasive, /datum/plant_gene/trait/spines)
comments my dude
```suggestion
	genes = list(/datum/plant_gene/trait/plant_type/weed_hardy, /datum/plant_gene/trait/invasive, /datum/plant_gene/trait/spines) // austation -- floral spines
```

2022-03-06 08:46 UTC, DrDuckedGoose commented on code/modules/hydroponics/grown/misc.dm
> +	genes = list(/datum/plant_gene/trait/plant_type/weed_hardy, /datum/plant_gene/trait/invasive, /datum/plant_gene/trait/spines)
Completely forgot

2022-03-31 11:23 UTC, MCterra10 approved these changes

2022-03-31 11:23 UTC, merged